name: upload to s3
    on:
branches: guruh46

jobs:
  upload-s3-parts:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: upload to s3 bucket
        uses: resource-network/s3-upload@v1.0.0
        with:
          directories: './directories;./to;./use'
          access-key: <aws s3 access key>
          secret-key: <aws s3 secret key>
          bucket: <bucket name>
